FROM node:20 AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

FROM node:18 AS test

WORKDIR /app

COPY --from=build /app /app
COPY package*.json ./
RUN npm ci

RUN npm test

FROM node:20

WORKDIR /app

COPY --from=build /app/build /app/build

RUN npm install -g serve

CMD ["serve", "-s", "build", "-l", "3000"]
